version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      VITE_DEV_SERVER_PORT: 5173
    command: ["npm", "run", "dev", "--", "--host"]


