services:
  app:
    build:
      context: ./backend/flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./backend/flask-app/app/app:/app
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=pass
      - SECRET_KEY=SECRET
    command: >
      sh -c "flask --app . run --debug --host=0.0.0.0"

  mongodb:
    image: mongo:6.0
    volumes:
      - dev-data:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"

  donut_service:
    build:
      context: ./donut_service
    ports:
      - "8000:80"
    volumes:
      - ./donut_service/app:/app
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=pass
      - SECRET_KEY=SECRET
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 80"

  redis:
    image: redis:7

  donut_worker:
    build:
      context: ./donut_service
    command: celery -A app.worker worker --pool=prefork --concurrency=1
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NVIDIA_VISIBLE_DEVICES=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 0
              capabilities: [gpu]
    depends_on:
      - donut_service
      - redis

  dashboard:
    build:
      context: ./donut_service
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - donut_service
      - redis

volumes:
  dev-data:
