version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - ./app/app/dist/static:/app/dist/static
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  proxy:
    build:
      context: ./proxy
    depends_on:
      - app
    ports:
      - "80:5000"
    volumes:
      - ./app/app/dist/static:/vol/static

volumes:
  mongo-data:

