services:
  app:
    build:
      context: .
    ports:
      - "5001:5000"  # Host port 5001 maps to container port 5000
    volumes:
      - ./app:/app  # Mount local app directory for development
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=pass
      - SECRET_KEY=SEKRETNY-KLUCZ-0MG  # Moved SECRET_KEY here
    command: >
      sh -c "flask --app . run --debug --host=0.0.0.0"

  mongodb:
    image: mongo:6.0
    volumes:
      - dev-data:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"

volumes:
  dev-data:
